name: Build
on:
  workflow_dispatch:
  
env:
  cache-version: v1.0.3

jobs:
  linux:
    name: build and test on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout abseil repository
        uses: actions/checkout@v4
        with:
          repository: 'abseil/abseil-cpp'
          fetch-depth: 0
          
      - name: build
        run: |
          mkdir build && cd build
          cmake -DABSL_BUILD_TESTING=ON -DABSL_USE_GOOGLETEST_HEAD=ON -DCMAKE_CXX_STANDARD=14 ..
          cmake --build . --target all

  macos:
    name: build and test on windows
    runs-on: windows-latest
    steps:
      - name: Checkout abseil repository
        uses: actions/checkout@v4
        with:
          repository: 'abseil/abseil-cpp'
          fetch-depth: 0

      - name: build
        shell: bash
        run: |
          mkdir build && cd build
          cmake -DABSL_BUILD_TESTING=ON -DABSL_USE_GOOGLETEST_HEAD=ON -DCMAKE_CXX_STANDARD=14 ..
          cmake --build . --target all
