name: Build
on:
  workflow_dispatch:
  
permissions:
  contents: write
  
env:
  cache-version: v1.0.3

jobs:
  linux:
    name: build and test on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout abseil repository
        uses: actions/checkout@v4
        with:
          repository: 'abseil/abseil-cpp'
          fetch-depth: 0
          
      - name: build
        run: |
          mkdir build && cd build
          mkdir install
          cmake -DABSL_BUILD_TESTING=ON -DABSL_USE_GOOGLETEST_HEAD=ON -DCMAKE_CXX_STANDARD=14 -DCMAKE_INSTALL_PREFIX=install ..
          cmake --build . --target all
          cmake install
          zip abseil_linux_x86_64.zip install
          
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: abseil_linux_x86_64 
          tag_name: ${{ env.GITHUB_SHA_SHORT }} 
          files: abseil_linux_x86_64.zip
          
  macos:
    name: build and test on windows
    runs-on: windows-latest
    steps:
      - name: Checkout abseil repository
        uses: actions/checkout@v4
        with:
          repository: 'abseil/abseil-cpp'
          fetch-depth: 0

      - name: build
        shell: bash
        run: |
          mkdir build && cd build
          mkdir install
          cmake -DABSL_BUILD_TESTING=ON -DABSL_USE_GOOGLETEST_HEAD=ON -DCMAKE_CXX_STANDARD=14 -DCMAKE_INSTALL_PREFIX=install ..
          cmake --build . --target ALL_BUILD
          cmake install
          7z a abseil_win_x86_64.zip install

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: abseil_win_x86_64 
          tag_name: ${{ env.GITHUB_SHA_SHORT }} 
          files: abseil_win_x86_64.zip
